name: Тестирование

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        node: [10, 12, 14]

    steps:
      - uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Использование Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  # Устанавливаем нужную версию Node.js

      - run: npm ci  # Устанавливаем зависимости (чистая установка)

      - run: |  # Выполняем сборку и тесты
          npm run build
          npm test
